### ISSUE TITLE
Package file filtering sometimes silently allows files that it shouldn't

### ISSUE THREAD

**Issue by squeek502** [luvit/lit#111]
Reproduceable by changing the ordering of the file filters in package.lua. Here's an example where luvit.exe is silently included. Both are using a directory with a package.lua, test.lua and luvit.exe as the only contents.

#### The broken example

package.lua:
```lua
return {
	name = "squeek502/test",
	version = "0.0.3",
	files = {
		"!tests",
		"**.lua"
	}
}
```

`lit add` output:
```
including: package.lua
including: test.lua
new tag: squeek502/test/v0.0.3
```

Output of a custom lit command that shows info about package in the local lit db:
```
squeek502/test@0.0.3
{ files = { '!tests', '**.lua' }, name = 'squeek502/test', version = '0.0.3' }
+ luvit.exe
+ package.lua
+ test.lua
```

#### The non-broken example

package.lua:
```lua
return {
	name = "squeek502/test",
	version = "0.0.4",
	files = {
		"**.lua",
		"!tests"
	}
}
```

`lit add` output:
```
including: package.lua
including: test.lua
new tag: squeek502/test/v0.0.4
```

Output of a custom lit command that shows info about package in the local lit db:
```
squeek502/test@0.0.4
{ files = { '**.lua', '!tests' }, name = 'squeek502/test', version = '0.0.4' }
+ package.lua
+ test.lua
```

**Comment by squeek502** [comment]
Also, here's the custom command in case you find it useful.

`commands/info.lua`
```lua
local config = require('autoconfig')
local makeDb = require('db')
local pkg = require('pkg')
local modes = require('git').modes

local db = makeDb(config.database)
local author = args[2]
local names = args[3]

if not names then
  names = {}
  for name in db.names(author) do
    table.insert(names, name)
  end
else
  names = {names}
end

local function getFullTree(hash, parentPath)
  local fullTree = {}
  local baseTree = db.loadAs("tree", hash)
  for _,file in ipairs(baseTree) do
    if parentPath then file.name = parentPath .. '/' .. file.name end
    table.insert(fullTree, file)
    if file.mode == modes.tree then
      local subTree = getFullTree(file.hash, file.name)
      for _,subfile in ipairs(subTree) do
        table.insert(fullTree, subfile)
      end
    end
  end
  return fullTree
end

for _,name in ipairs(names) do
  for version in db.versions(author, name) do
    local meta, kind, hash = pkg.queryDb(db, db.read(author, name, version))
    local tree = getFullTree(hash)

    print("\n" .. meta.name .. "@" .. meta.version)
    p(meta)
    for _,file in ipairs(tree) do
      print("  " .. file.name)
    end
  end
end
```

**Comment by squeek502** [comment]
In poking around, there seems to be a lot of weird stuff in the filtering system.

 * All rules are compiled into a single filter
 * [Only the first rule determines the filter's `default` field](https://github.com/luvit/lit/blob/master/libs/rules.lua#L59). This is one cause of the problem (the `default` is what's allowing luvit.exe through, so that's why the ordering matters).
 * The [confusingly named `subPath` variable is only set when a filter matches](https://github.com/luvit/lit/blob/master/libs/rules.lua#L87), and [subPath being set is what determines if the 'including' or 'skipping' strings are printed](https://github.com/luvit/lit/blob/master/libs/rules.lua#L106-L112). This is the cause of the silent part of the problem.
 * [`rules.isAllowed` is set up to handle a table of filters](https://github.com/luvit/lit/blob/master/libs/rules.lua#L80), but the logic doesn't make any sense for handling a table of filters (the variable states would become a mismash of the various filters, and the last filter would take precedence).

I don't really know how to fix it, because I can't really figure out what it's trying to do in the first place.

**Comment by creationix** [comment]
So yes, as you've seen, the order does matter in that the first rule determines if it's a white-list of black-list.  If the first item is a positive include, filters assume you want a white list (otherwise why would you start out by including a file explicitly).  By that same logic, if the first rule is filtering something out, we assume it's a black list (everything not excluded is assumed to be included).

After that, the latest rules take precedence over earlier rules so that you can do complex things like include all *.lua files, except exclude files starting with Z except include ZZ.lua.

```lua
{
  "*.lua",
  "!Z*.lua",
  "ZZ.lua",
}
```

So you see it's a hierarchy of rules, not a linear list.

Also if the filters system find a new package.lua deeper inside with it's own rules, those have higher precedence for their sub-folders.

On the silencing logic, I felt it was overly verbose to show all files included or excluded and opted to only show the exceptions to the rule.  So in a black-list as in your broken example, the default is to include everything.  That's why it doesn't log every file included.

I can see where better docs help here a lot.  Also if there is anything with this system that doesn't work for your use case, let me know.  It's fairly advanced to allow for a wide range of use cases.

**Comment by squeek502** [comment]
Ah, alright, thanks for explaining. [I should have read this wiki article](https://github.com/luvit/lit/wiki/Package-Metadata).

I think the output could make things less confusing, though, with a few changes:

* Never silently include files; any file that is included should get an `including x` output line. Skipped files that are not specifically excluded by a filter are fine to leave out of the output.
* Output a line denoting whether or not the filter is interpreted as a whitelist or blacklist (and why). A single line at the top of `lit add` output saying something like `first rule is positive, filter treated as a whitelist` or `first rule is negative, filter treated as a blacklist` would make things much more intuitive.

**Comment by squeek502** [comment]
Better wording for the whitelist/blacklist stuff:

```
if filter.default then
  log("first rule is exclusionary", "including all by default")
else
  log("first rule is inclusionary", "excluding all by default")
end
```

**Comment by creationix** [comment]
Thanks for the feedback. Hopefully the new behaviour is less surprising.

**Comment by creationix** [comment]
Re-open since my code had a bug.
