### ISSUE TITLE
On a lit add, ignore dependency modules

### ISSUE THREAD

**Issue by rphillips** [luvit/lit#18]
... or something similar. Right now all dependencies get added in a dirty tree.

**Comment by creationix** [comment]
Since lit installs deps in a flat tree, it doesn't expect a deep hierarchy to also contain other lit modules.  I'd rather not ignore `modules` inside a library by default.

I do intend to add some sort of whitelist/blacklist feature so authors can control what files are included.

Another idea is to scan code for require statements and try to auto-guess the needed files as the default behavior.  If authors need more control, then they can specify the white/black list.

**Comment by creationix** [comment]
Ok, I decided this was a good feature.  I'm going to add the default to ignore "modules" and later we can implement white-list/black-lists.
